### ISSUE TITLE
Not doing anything other then refreshing the tab.

### ISSUE THREAD

**Issue by Durmwind** [Onestay/CR-Unblocker#24]
Was so excited when i found this. But it does nothing other then randomly refresh my current tab.
I tried reinstalling, restarting and anything else i could think of.

Is there any info i could give that would help you identify the problem.

**Comment by Onestay** [comment]
Uhmm, you picked a good moment to find it. My server is currently experiencing problems and the backup server setup doesn't seem to work. I'm working on resolving this problem.

**Comment by Durmwind** [comment]
Wow, that was a quick answer. please tell me if there is anything i can do to provide more info or to help. 
Thanks for all your efforts.

**Comment by Onestay** [comment]
It should be fixed now. Could you check that real quick since I can't access my computer right now?

**Comment by megonemad1** [comment]
i still appear to be suffering from the problem, also i get the restriction error on shows like one piece

**Comment by Blightwidow** [comment]
We are resolving some issues on servers and will update the extension soon to be more reliable.

**Comment by Durmwind** [comment]
Works like a charm now.
Thank you so much for your quick replies, the quick fix and your impecabble vigilance
